### ISSUE TITLE
Screen turns black shortly and then the detector stops working.

### ISSUE THREAD

**Issue by FrankenApps** [ModelDepot/tfjs-yolo-tiny-demo#2]
I have only tested this on my Win 10 Computer, but it happens both in my local running version and in the hosted version. What happens is:
1. Everything works fine for 1-2 minutes
2. Suddenly the browser screen turns black (taskbar stays visible) for about one second
3. Everything **seems** to work again, but from now, until I reload the page, no more objects are detected

**Comment by FrankenApps** [comment]
Oh sorry,
I did just now see, this issue was already reported in the main repo. Btw. im on Chrome 66, too.

**Comment by MikeShi42** [comment]
Hello! I'm unsure of which issue you're referring to that's relevant for this issue. I'd suspect that the script crashed at some point and stopped making predictions. Any chance you could check if there are any errors in the console?

**Comment by FrankenApps** [comment]
I meant the WebGL: CONTEXT_LOST_WEBGL error. This is what I get in the console after running the example for ~2 minutes:
![unbenannt](https://user-images.githubusercontent.com/17967303/39940626-304989b8-555a-11e8-85aa-9335b4b1e1d9.png)
