### ISSUE TITLE
Couldn't manage to clone then run locally or on Glitch either on Chrome or Firefox

### ISSUE THREAD

**Issue by Utopiah** [ModelDepot/tfjs-yolo-tiny-demo#4]
Cloning the repository and building locally with node v10.1.0 fails me with : 

Firefox
![image](https://user-images.githubusercontent.com/1076655/40269904-c7cd6ef0-5b84-11e8-9969-52428f447525.png)

Chrome
![image](https://user-images.githubusercontent.com/1076655/40269911-f48fc4ec-5b84-11e8-9776-f8e98811e0ce.png)

Also tried on Glitch but couldn't even run it getting a "/etc/app-types/node/start.sh: line 43: null: command not found". I briefly tried in the console to do a `npm run serve` but it didn't end.

**Comment by MikeShi42** [comment]
Seems odd, what tf.js version are you running? If it's 0.11/10 can you try downgrading to 0.9? Also would you mind opening this issue on https://github.com/ModelDepot/tfjs-yolo-tiny? Going to be closing the issues on this repo to keep everything consolidated :)

**Comment by Utopiah** [comment]
Ah I posted here because I assumed it was more related to the demo/web part rather than model use. Raising the issue there instead.
