### ISSUE TITLE
Advice needed when using single image

### ISSUE THREAD

**Issue by okramovic** [ModelDepot/tfjs-yolo-tiny-demo#5]
Hi,

I'm trying to rewrite your code so I could upload an image file using file input element instead of webcam. I tried adapting your webcam class functions so I process the image before I pass it to 'run' function, but I get following error:

> Uncaught (in promise) Error: Error when checking : expected input_1 to have shape [null,416,416,3] but got array with shape [1,460,460,3].
>     at new ValueError (tfjs-yolo-tiny-demo.js:16807)
>     at checkInputData (tfjs-yolo-tiny-demo.js:21558)
>     at Model.predict (tfjs-yolo-tiny-demo.js:21849)
>     at tfjs-yolo-tiny-demo.js:27878
>     at Object.Tracking.tidy (tfjs-yolo-tiny-demo.js:8336)
>     at tfjs-yolo-tiny-demo.js:27878
>     at b (tfjs-yolo-tiny-demo.js:27878)
>     at Generator._invoke (tfjs-yolo-tiny-demo.js:27878)
>     at Generator.t.(:1234/anonymous function) [as next] (http://localhost:1234/dist/tfjs-yolo-tiny-demo.js:27878:23324)
>     at n (tfjs-yolo-tiny-demo.js:27878)
> 

Any idea what I'm missing out? Seems like it could be just something small (I know nothing about the field till now so I'm sorry if it's something super obvious...)

**Comment by MikeShi42** [comment]
Hello! No worries, so it seems like the image has the wrong size, the model itself usually isn't flexible to the input size of the image, so you have to do a bit of pre-processing to resize the image to the correct shape/dimensions. The error says the model expects "shape" [null, 416, 416, 3], which just means an RGB (3 channel) color image of 416x416px (the null being the batch size which is set to any, you don't have to worry about that). Your image is currently 460x460px, so you can just resize it to 416x416 and it should work.

**Comment by okramovic** [comment]
Thank you! So I made it work when image is part of DOM, but I'm trying to make it work also with newly 'uploaded' image (using input type file), reading it as dataURL using file reader, but it does not work. Is there any simple way of doing that? How should I read the file?

**Comment by okramovic** [comment]
help..!

**Comment by MikeShi42** [comment]
@okramovic I'm not sure how to advise you here, I think this seems like a generic implementation issue. In light of that, I can only say perhaps the TF.js user group can help you out or a post on Stackoverflow.
